version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: vision_laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
      - central-db-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-mysql-central-1
      - DB_PORT=3306
      - DB_DATABASE=vision_db
      - DB_USERNAME=root
      - DB_PASSWORD=password

  webserver:
    image: nginx:alpine
    container_name: vision-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
      - central-db-network # Connect to the central MySQL network
    depends_on:
      - app

networks:
  laravel:
  central-db-network:
    external: true # Use the external central MySQL network
